@startuml
class Backtest {
    + Backtest(setting:Setting.Exchange, repository:ICandleRepository)
    + <<async>> Buy(quantity:float) : Task<Position>
    + <<async>> ClosePosition(position:Position) : Task<decimal>
    + <<async>> ClosePositionAll() : Task<decimal>
    + <<async>> Sell(quantity:float) : Task<Position>
}
class "List`1"<T> {
}
class "IConnectableObservable`1"<T> {
}
IExchange <|-- Backtest
Backtest --> "Positions<Position>" "List`1"
Backtest --> "OnPulled<Candle>" "IConnectableObservable`1"
Backtest --> "Symbol" Symbol
@enduml
