@startuml
interface IExchange {
    + Buy(quantity:float) : Task<Position>
    + Sell(quantity:float) : Task<Position>
    + {abstract} ClosePosition(position:Position) : Task<decimal>
    + {abstract} ClosePositionAll() : Task<decimal>
}
class "List`1"<T> {
}
class "IConnectableObservable`1"<T> {
}
IExchange --> "Positions<Position>" "List`1"
IExchange --> "OnPulled<Candle>" "IConnectableObservable`1"
IExchange --> "Symbol" Symbol
@enduml
