@startuml
enum Timeframe {
    OneMinute= 1,
    FiveMinute= 5,
    FifteenMinute= 15,
    OneHour= 60,
    FourHour= 240,
    OneDay= 1440,
}
class TimeframeExtensions <<static>> <<partial>> {
    + {static} ToTimeSpan(timeframe:Timeframe) : TimeSpan
}
@enduml
