@startuml
class "RingQueue`1"<T> {
    + Count : int <<get>>
    + Capacity : int <<get>>
    + RingQueue(capacity:int)
    + Enqueue(item:T) : void
    + Dequeue() : T
    + Peek() : T
    + GetEnumerator() : IEnumerator<T>
}
class "IEnumerable`1"<T> {
}
"IEnumerable`1" "<T>" <|-- "RingQueue`1"
@enduml
