@startuml
class Backtest {
    + Backtest(setting:ExchangeSetting, repository:ICandleRepository)
    + Buy(quantity:float) : Task<Position>
    + ClosePosition(position:Position) : Task<decimal>
    + ClosePositionAll() : Task<decimal>
    + Sell(quantity:float) : Task<Position>
}
class "List`1"<T> {
}
class "IConnectableObservable`1"<T> {
}
IExchange <|-- Backtest
Backtest --> "Positions<Position>" "List`1"
Backtest --> "Place" ExchangePlace
Backtest --> "OnPulled<Candle>" "IConnectableObservable`1"
Backtest --> "Symbol" Symbol
@enduml
