@startuml
!include ./Test/CandleRepositoryTest.puml
!include ./Common/src/EnumStringAttribute.puml
!include ./Common/src/RingQueue.puml
!include ./Domain/src/Bot.puml
!include ./Domain/src/Candle.puml
!include ./Domain/src/ExchangePlace.puml
!include ./Domain/src/GraphType.puml
!include ./Domain/src/ICandleRepository.puml
!include ./Domain/src/IExchange.puml
!include ./Domain/src/ITradeLogger.puml
!include ./Domain/src/Position.puml
!include ./Domain/src/Setting.puml
!include ./Domain/src/Symbol.puml
!include ./Domain/src/Timeframe.puml
!include ./Infra/src/BotFactory.puml
!include ./Infra/src/ExchangeContainer.puml
!include ./Infra/src/PastCandelRepository.puml
!include ./Infra/src/TradeHistoryReporter.puml
!include ./Domain/src/Strategies/AnalysisData.puml
!include ./Domain/src/Strategies/AnalysisValue.puml
!include ./Domain/src/Strategies/MACross.puml
!include ./Domain/src/Strategies/Strategy.puml
!include ./Domain/src/Strategies/StrategyActionType.puml
!include ./Domain/src/Strategies/StrategyKind.puml
!include ./Domain/src/Strategies/StrategyUtility.puml
!include ./Infra/src/Exchanges/Backtest.puml
!include ./Infra/src/Exchanges/RealExchange.puml
!include ./Application/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Application/obj/Debug/net6.0/Application.AssemblyInfo.puml
!include ./Application/obj/Debug/net6.0/Application.GlobalUsings.g.puml
!include ./Application/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Application/obj/Debug/net8.0/Application.AssemblyInfo.puml
!include ./Application/obj/Debug/net8.0/Application.GlobalUsings.g.puml
!include ./Common/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Common/obj/Debug/net8.0/Common.AssemblyInfo.puml
!include ./Common/obj/Debug/net8.0/Common.GlobalUsings.g.puml
!include ./Domain/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Domain/obj/Debug/net6.0/Domain.AssemblyInfo.puml
!include ./Domain/obj/Debug/net6.0/Domain.GlobalUsings.g.puml
!include ./Domain/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Domain/obj/Debug/net8.0/Domain.AssemblyInfo.puml
!include ./Domain/obj/Debug/net8.0/Domain.GlobalUsings.g.puml
!include ./Infra/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Infra/obj/Debug/net6.0/Infra.AssemblyInfo.puml
!include ./Infra/obj/Debug/net6.0/Infra.GlobalUsings.g.puml
!include ./Infra/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Infra/obj/Debug/net8.0/Infra.AssemblyInfo.puml
!include ./Infra/obj/Debug/net8.0/Infra.GlobalUsings.g.puml
!include ./Presentation/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Presentation/obj/Debug/net8.0/Presentation.AssemblyInfo.puml
!include ./Presentation/obj/Debug/net8.0/Presentation.GlobalUsings.g.puml
!include ./Test/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Test/obj/Debug/net8.0/Test.AssemblyInfo.puml
!include ./Test/obj/Debug/net8.0/Test.GlobalUsings.g.puml
@enduml
