#!/bin/sh
# pre-commit hook to run dotnet format

# Run dotnet format
dotnet format server/src/BotTrade.sln

# Capture the exit code of dotnet format
FORMAT_EXIT_CODE=$?

if [ $FORMAT_EXIT_CODE -ne 0 ]; then
    echo "dotnet format detected changes. Please review and commit again."
    exit 1
fi

exit 0
