@startuml
class BotSetting <<record>> {
    + Lot : float <<get>> <<set>>
    + IsTakeableMultiPosition : bool <<get>> <<set>>
    + ReportDir : string <<get>>
}
class "IEnumerable`1"<T> {
}
BotSetting --> "Exchange" ExchangeSetting
BotSetting --> "Strategies<StrategySetting>" "IEnumerable`1"
@enduml
