@startuml
class StrategyReport {
    + PnL : decimal <<get>>
    + ProfitAverage : decimal <<get>>
    + LossAverage : decimal <<get>>
    + MaxWinStreak : int <<get>>
    + MaxLossStreak : int <<get>>
    + WinRate : float <<get>>
    + MaxDrawdown : decimal <<get>>
    + RiskReward : decimal <<get>>
    + StrategyReport(trades:IEnumerable<Position>?)
    + Log(position:Position) : void
}
class "IEnumerable`1"<T> {
}
StrategyReport --> "Trades<Position>" "IEnumerable`1"
@enduml
